In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("bvmcancer.csv")
dataset.drop(dataset.columns[[0,32]],axis=1,inplace=True)
np.random.seed(55)
dataset.head(10)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   
5         M        12.45         15.70           82.57      477.1   
6         M        18.25         19.98          119.60     1040.0   
7         M        13.71         20.83           90.20      577.9   
8         M        13.00         21.82           87.50      519.8   
9         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   
5         0.2087  ...         15.47          23.75           103.40   
6         0.1794  ...         22.88          27.66           153.20   
7         0.2196  ...         17.06          28.14           110.60   
8         0.2350  ...         15.49          30.73           106.20   
9         0.2030  ...         15.09          40.68            97.65   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   
5       741.6            0.1791             0.5249           0.5355   
6      1606.0            0.1442             0.2576           0.3784   
7       897.0            0.1654             0.3682           0.2678   
8       739.3            0.1703             0.5401           0.5390   
9       711.4            0.1853             1.0580           1.1050   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  
5                0.1741          0.3985                  0.12440  
6                0.1932          0.3063                  0.08368  
7                0.1556          0.3196                  0.11510  
8                0.2060          0.4378                  0.10720  
9                0.2210          0.4366                  0.20750  

[10 rows x 31 columns]

In [3]:
x=dataset.iloc[:,1:].values
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [4]:
y=dataset.iloc[:,0].values
print(y)

['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M'
 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B

In [5]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
print(x_train)

[[ 1.85189846  1.81243805  1.84719821 ...  1.59086136  0.64298133
  -0.40633689]
 [ 0.09575123 -0.56566089 -0.02391154 ... -1.23476037 -0.69341836
  -1.21488847]
 [-0.32619954 -0.71058001 -0.36536751 ... -0.85458242  1.19036275
  -0.711148  ]
 ...
 [ 0.14923795  1.37530498  0.2136418  ...  0.11955561  0.50490313
   0.98296008]
 [-0.05876596 -1.40904263 -0.12048494 ... -0.85116439 -0.09343572
  -0.8544627 ]
 [ 3.99731014  1.67939755  4.14081662 ...  2.32573742 -0.39260515
  -0.51596194]]


In [8]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(128,input_dim=30,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=5,epochs=100) 

Epoch 1/100
80/80 [==============================] - 5s 4ms/step - loss: 0.1837 - accuracy: 0.9347
Epoch 2/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0737 - accuracy: 0.9749
Epoch 3/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0577 - accuracy: 0.9849
Epoch 4/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0420 - accuracy: 0.9849
Epoch 5/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0341 - accuracy: 0.9874
Epoch 6/100
80/80 [==============================] - 0s 5ms/step - loss: 0.0334 - accuracy: 0.9899
Epoch 7/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0204 - accuracy: 0.9950
Epoch 8/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0161 - accuracy: 0.9925
Epoch 9/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0124 - accuracy: 0.9975
Epoch 10/100
80/80 [==============================] - 0s 4ms/step - loss: 0.0085 - accuracy: 1.0000
Epoch 11/

In [9]:
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(128,input_dim=30,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='sgd',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=10,epochs=100) 

Epoch 1/100
40/40 [==============================] - 3s 5ms/step - loss: 0.6161 - accuracy: 0.7889
Epoch 2/100
40/40 [==============================] - 0s 4ms/step - loss: 0.4707 - accuracy: 0.9095
Epoch 3/100
40/40 [==============================] - 0s 7ms/step - loss: 0.3584 - accuracy: 0.9246
Epoch 4/100
40/40 [==============================] - 0s 4ms/step - loss: 0.2765 - accuracy: 0.9372
Epoch 5/100
40/40 [==============================] - 0s 4ms/step - loss: 0.2212 - accuracy: 0.9447
Epoch 6/100
40/40 [==============================] - 0s 3ms/step - loss: 0.1845 - accuracy: 0.9497
Epoch 7/100
40/40 [==============================] - 0s 4ms/step - loss: 0.1591 - accuracy: 0.9548
Epoch 8/100
40/40 [==============================] - 0s 6ms/step - loss: 0.1410 - accuracy: 0.9623
Epoch 9/100
40/40 [==============================] - 0s 6ms/step - loss: 0.1275 - accuracy: 0.9598
Epoch 10/100
40/40 [==============================] - 0s 6ms/step - loss: 0.1172 - accuracy: 0.9648
Epoch 11/

40/40 [==============================] - 0s 5ms/step - loss: 0.0199 - accuracy: 0.9950
Epoch 84/100
40/40 [==============================] - 0s 4ms/step - loss: 0.0195 - accuracy: 0.9950
Epoch 85/100
40/40 [==============================] - 0s 4ms/step - loss: 0.0191 - accuracy: 0.9975
Epoch 86/100
40/40 [==============================] - 0s 4ms/step - loss: 0.0187 - accuracy: 0.9950
Epoch 87/100
40/40 [==============================] - 0s 3ms/step - loss: 0.0184 - accuracy: 0.9975
Epoch 88/100
40/40 [==============================] - 0s 4ms/step - loss: 0.0179 - accuracy: 0.9975
Epoch 89/100
40/40 [==============================] - 0s 4ms/step - loss: 0.0177 - accuracy: 0.9950
Epoch 90/100
40/40 [==============================] - 0s 5ms/step - loss: 0.0173 - accuracy: 0.9975
Epoch 91/100
40/40 [==============================] - 0s 4ms/step - loss: 0.0170 - accuracy: 0.9950
Epoch 92/100
40/40 [==============================] - 0s 3ms/step - loss: 0.0167 - accuracy: 0.9950
Epoch 93/100


In [10]:
y_pred =model.predict(x_test)
y_pred = (y_pred > 0.5)

6/6 [==============================] - 6s 4ms/step


In [11]:
from sklearn.metrics import confusion_matrix
results=confusion_matrix(y_test,y_pred)

In [12]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
print("Confusion Matrix")
print(results) 
print("Accuracy Score :")
print(accuracy_score(y_test,y_pred))
print("Report:")
print(classification_report(y_test,y_pred))

Confusion Matrix
[[  0 102]
 [  0  69]]
Accuracy Score :
0.40350877192982454
Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       102
           1       0.40      1.00      0.57        69

    accuracy                           0.40       171
   macro avg       0.20      0.50      0.29       171
weighted avg       0.16      0.40      0.23       171



C:\Users\prakr\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\prakr\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\prakr\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
